<?php
$suppliers = [
    [ 'A.C.B AS', 'Construction', 'Latvia' ],
    [ 'Aarsleff Rail', 'Construction', 'Denmark' ],
    [ 'ABB SIA', 'Energetics', 'Latvia' ],
    [ 'ACCIONA Infarstructuras S.A.', 'Construction', 'Spain' ],
    [ 'Acte Rail', 'Construction', 'Denmark' ],
    [ 'AECOM', 'Architecture and design', 'Latvia' ],
    [ 'AMPLEXOR Latvia', 'Other', 'Latvia' ],
    [ 'Ardanuy Ingenieria S.A.', 'Architecture and design', 'Lithuania' ],
    [ 'Ardanuy Ingenieria S.A.', 'Architecture and design', 'Spain' ],
    [ 'Assecor Baltic SIA', 'IT and communications', 'Latvia' ],
    [ 'Balfour Beatty', 'Architecture and design', 'United Kingdom' ],
    [ 'Baltic Development Consultancy', 'Consulting', 'Latvia' ],
    [ 'Baltijas Gumijas Fabrika JSC', 'Manufacturing, production industry', 'Latvia' ],
    [ 'BDO', 'Consulting', 'Latvia' ],
    [ 'Bentley Systems Ltd.', 'IT and communications', 'United Kingdom' ],
    [ 'BMGS AS', 'Construction', 'Latvia' ],
    [ 'Bombardier Transportation Baltics SIA', 'Manufacturing, production industry', 'Latvia' ],
    [ 'Bomis Ltd', 'Transportation, logistics and storage', 'Latvia' ],
    [ 'BUILDIMPEKS SIA', 'Construction', 'Latvia' ],
    [ 'CCEF (French Trade Advisors)', 'Transportation, logistics and storage', 'Latvia' ],
    [ 'CEMEX SIA', 'Manufacturing, production industry', 'Latvia' ],
    [ 'CERTIFER SA', 'Consulting', 'France' ],
    [ 'CH2M', 'Consulting', 'United Kingdom' ],
    [ 'China Harbour Engineering Company Latvia LTD.', 'Construction', 'Latvia' ],
    [ 'China Railway Construction Corporation', 'Construction', 'Estonia' ],
    [ 'China Railway International Co. Ltd.', 'Consulting', 'China' ],
    [ 'Citrus Solutions SIA', 'Other', 'Latvia' ],
    [ 'Colliers International Latvia', 'Consulting', 'Latvia' ],
    [ 'COMSA', 'Construction', 'Spain' ],
    [ 'Construcciones y Auxiliar de Ferrocarriles S.A. (CAF S.A.)', 'Transportation, logistics and storage', 'Spain' ],
    [ 'COWI A/S', 'Consulting', 'Denmark' ],
    [ 'CSE COE', 'Consulting', 'Latvia' ],
    [ 'DANOBAT', 'Manufacturing, production industry', 'Spain' ],
    [ 'Danske Bank AS', 'Finance and insurance', 'Latvia' ],
    [ 'Datu Tehnoloģiju Grupa SIA', 'IT and communications', 'Latvia' ],
    [ 'DB Engineering & Consulting GmbH', 'Consulting', 'Lithuania' ],
    [ 'DHL', 'Transportation, logistics and storage', 'Latvia' ],
    [ 'Domuss SIA', 'Real estate', 'Latvia' ],
    [ 'Eiroeksperts SIA', 'Real estate', 'Latvia' ],
    [ 'ELECNOR', 'Construction', 'Spain' ],
    [ 'Ellex Kļaviņš', 'Law and regulations', 'Latvia' ],
    [ 'Ellex Valiunas ir partneriai', 'Law and regulations', 'Lithuania' ],
    [ 'Energocomplekt', 'Energetics', 'Belarus' ],
    [ 'ENERGOREMONTS RIGA', 'Construction', 'Latvia' ],
    [ 'ENGIE', 'Energetics', 'France' ],
    [ 'ENGIE INEO', 'Construction', 'Denmark' ],
    [ 'ERICSSON Latvia', 'IT and communications', 'Latvia' ],
    [ 'Ernst & Young Baltic SIA', 'Consulting', 'Latvia' ],
    [ 'ERR', 'Media and information services', 'Estonia' ],
    [ 'Estonian Railways Ltd', 'Transportation, logistics and storage', 'Estonia' ],
    [ 'Europejskie Konsorcjum Kolejowe WAGON Sp. z o.o.', 'Transportation, logistics and storage', 'Poland' ],
    [ 'Eurovia Lietuva PLC ', 'Construction', 'Lithuania' ],
    [ 'FIMA SIA', 'Construction', 'Latvia' ],
    [ 'FIMA UAB', 'IT and communications', 'Lithuania' ],
    [ 'FinBalt Consulting SIA', 'Consulting', 'Latvia' ],
    [ 'Finnish Transport Agency', 'Public sector, government', 'Finland' ],
    [ 'First Glass Company', 'Architecture and design', 'Latvia' ],
    [ 'GEFCO Baltic', 'Transportation, logistics and storage', 'Latvia' ],
    [ 'Geležinkelių projektavimas UAB', 'Architecture and design', 'Lithuania' ],
    [ 'Global Insulator Group Holding', 'Manufacturing, production industry', 'Estonia' ],
    [ 'grupa93', 'Architecture and design', 'Latvia' ],
    [ 'GULERMAK', 'Construction', 'Poland' ],
    [ 'Helusta OU', 'Wholesale and retail trade', 'Estonia' ],
    [ 'Helusta UAB', 'Wholesale and retail trade', 'Lithuania' ],
    [ 'Helux SIA', 'Wholesale and retail trade', 'Latvia' ],
    [ 'Hidrolab', 'Other', 'Latvia' ],
    [ 'Hydrema', 'Construction', 'Denmark' ],
    [ 'IDOM Consulting, Engineering, Architecture', 'Architecture and design', 'Spain' ],
    [ 'IIZI BROKERS', 'Finance and insurance', 'Latvia' ],
    [ 'Inabensa', 'Construction', 'Spain' ],
    [ 'INDRA SISTEMAS, S.A.', 'IT and communications', 'Spain' ],
    [ 'INNOLAIN OOO', 'Architecture and design', 'Russia' ],
    [ 'INNOYAR', 'IT and communications', 'Japan' ],
    [ 'Instalaciones Inabensa', 'Construction', 'Spain' ],
    [ 'Julena ltd', 'Consulting', 'Latvia' ],
    [ 'KATISS SIA', 'Construction', 'Latvia' ],
    [ 'Kauno tiltai', 'Construction', 'Lithuania' ],
    [ 'Kellme Engineering', 'Architecture and design', 'Latvia' ],
    [ 'Kelprojektas, JSC', 'Architecture and design', 'Lithuania' ],
    [ 'KPMG Law Firm', 'Consulting', 'Latvia' ],
    [ 'Latio', 'Real estate', 'Latvia' ],
    [ 'Lattelecom', 'IT and communications', 'Latvia' ],
    [ 'Lemminkäinen Eesti', 'Construction', 'Estonia' ],
    [ 'Lemminkäinen Infra Oy', 'Construction', 'Finland' ],
    [ 'Lemminkainen Latvija', 'Construction', 'Latvia' ],
    [ 'Leonhard Moll Betonwerke GmbH + Co KG', 'Manufacturing, production industry', 'Germany' ],
    [ 'Linstow Center Management Ltd.', 'hide', 'Latvia' ],
    [ 'LNK Industries AS', 'Construction', 'Latvia' ],
    [ 'LOHR Industrie', 'hide', 'France' ],
    [ 'M2 LTD', 'Construction', 'Latvia' ],
    [ 'Merko Ehitus Eesti AS', 'Construction', 'Estonia' ],
    [ 'Merks Ltd', 'Construction', 'Latvia' ],
    [ 'Meta Advisory Group', 'Media and information services', 'Estonia' ],
    [ 'Mitnija JSC', 'Construction', 'Lithuania' ],
    [ 'MOOZHS NP SRO', 'Law and regulations', 'Russia' ],
    [ 'Movares Europe bv', 'Consulting', 'Netherlands' ],
    [ 'MRSERV', 'Consulting', 'Latvia' ],
    [ 'Nordecon AS', 'Construction', 'Estonia' ],
    [ 'Nordic Investment Bank', 'Finance and insurance', 'Finland' ],
    [ 'OLIMPS', 'Architecture and design', 'Latvia' ],
    [ 'OR Consulting Ltd.', 'Consulting', 'Lithuania' ],
    [ 'PANEVĖŽIO KELIAI JSC', 'Construction', 'Lithuania' ],
    [ 'Peikko Latvija SIA', 'Wholesale and retail trade', 'Latvia' ],
    [ 'Peikko Lietuva UAB', 'Manufacturing, production industry', 'Lithuania' ],
    [ 'PET Baltija', 'Manufacturing, production industry', 'Latvia' ],
    [ 'PINTSCH Aben / PINTSCH Tiefenbach', 'Manufacturing, production industry', 'Germany' ],
    [ 'Plasser & Theurer', 'Manufacturing, production industry', 'Latvia' ],
    [ 'Plastwil Sp. z o.o.', 'Manufacturing, production industry', 'Poland' ],
    [ 'Prospect\'s SIA', 'Real estate', 'Latvia' ],
    [ 'Railistics GmbH', 'Consulting', 'Germany' ],
    [ 'Ramboll Finland Oy', 'Consulting', 'Finland' ],
    [ 'Ramirent Baltic AS', 'Construction', 'Latvia' ],
    [ 'REM PRO SIA', 'Architecture and design', 'Latvia' ],
    [ 'RERE GRUPA', 'Construction', 'Latvia' ],
    [ 'Rosenfelt & West Engineering A/S', 'Consulting', 'Denmark' ],
    [ 'SAP Latvia', 'IT and communications', 'Latvia' ],
    [ 'Schenker SIA', 'Transportation, logistics and storage', 'Latvia' ],
    [ 'SEB', 'Finance and insurance', 'Latvia' ],
    [ 'Shipley Denmark', 'Consulting', 'Denmark' ],
    [ 'Shipley Estonia OÜ', 'Consulting', 'Estonia' ],
    [ 'Siemens Lithuania', 'Energetics', 'Lithuania' ],
    [ 'Siemens Osakeyhtio Estonian Branch', 'Transportation, logistics and storage', 'Estonia' ],
    [ 'Siemens Osakeyhtio Latvian Branch', 'Transportation, logistics and storage', 'Latvia' ],
    [ 'SIGMEN SIA', 'Wholesale and retail trade', 'Latvia' ],
    [ 'SJSC Riga International Airport', 'Transportation, logistics and storage', 'Latvia' ],
    [ 'Skinest Baltija JSC', 'Wholesale and retail trade', 'Lithuania' ],
    [ 'Skonto Būve SIA', 'Construction', 'Latvia' ],
    [ 'Sorainen', 'Law and regulations', 'Latvia' ],
    [ 'STRABAG', 'Construction', 'Latvia' ],
    [ 'SU №308 OAO', 'Construction', 'Russia' ],
    [ 'Swedbank AB', 'Finance and insurance', 'Lithuania' ],
    [ 'SYSTRA', 'Architecture and design', 'France' ],
    [ 'Talleres Alegria, s.a.', 'Manufacturing, production industry', 'Spain' ],
    [ 'Thales Rail Signalling Solutions Baltics', 'Construction', 'Latvia' ],
    [ 'Thales Transporatation Systems GmbH', 'Transportation, logistics and storage', 'Germany' ],
    [ 'The Nichols Group', 'Consulting', 'United Kingdom' ],
    [ 'Tiflex Ltd ', 'Manufacturing, production industry', 'United Kingdom' ],
    [ 'Tiltu ekspertu centras UAB', 'Architecture and design', 'Lithuania' ],
    [ 'TRACK TEC S.A.', 'Manufacturing, production industry', 'Poland' ],
    [ 'TRINITI', 'Law and regulations', 'Latvia' ],
    [ 'Vestaka JSC', 'Transportation, logistics and storage', 'Lithuania' ],
    [ 'Vīlands Associates SIA', 'Consulting', 'Latvia' ],
    [ 'VILGERTS', 'Law and regulations', 'Latvia' ],
    [ 'voestalpine VAE RIGA, SIA ', 'Manufacturing, production industry', 'Latvia' ],
    [ 'VR Track Oy', 'Consulting', 'Finland' ],
    [ 'Witteveen+Bos Latvia', 'Consulting', 'Latvia' ],
    [ 'Witteveen+Bos Raadgevende Ingenieurs bv', 'Consulting', 'Netherlands' ],
];
return [
    'on' => [
        'table'      => 'suppliers',
        'fields'     => [
            'id' => 'increments',
            'company' => 'string:250|nullable',
            'industry' => 'string:250|nullable',
            'state' => 'string:250|nullable',
        ],
        'index'      => [
            'key' => [
                'company'
            ],
        ],
        'posthook'   => function () use ($suppliers) {
            foreach($suppliers as $supplier) {
                (new Suppliers())->create([
                    'company' => $supplier[0],
                    'industry' => $supplier[1],
                    'state' => $supplier[2],
                ]);
            }
        }
    ],

    'down' => [
        'table'      => 'suppliers',
        'drop'       => true,
        'index'      => [
            'company'
        ],
    ]
];